### ISSUE TITLE
Long delay when switching baud rate back and forth

### ISSUE THREAD

**Issue by GuenterNo** [gicking/LIN_master_Arduino#6]
Using the LIN_blocking example on an ESP32.

I noticed a delay of about 11ms between the BREAK signal and the SYNC signal.
I could not yet check if such a long delay is permitted, but I have never seen such a delay before.

The root cause is that the call
pSerial->begin(baudrate)
takes 10 milliseconds. Why? This crashes the performance of the LIN interface.
The while loop after the begin() takes no time.

**Comment by gicking** [comment]
see comment in [Issue 5](https://github.com/gicking/LIN_master_Arduino/issues/5). This should also be solved. Please let me know if it works now

**Comment by GuenterNo** [comment]
The long delay is now gone by replacing pSerial->begin() with pSerial->UpdateBaudRate. The signal looks normal on the scope now. Still to be tested with a real LIN device.

**Comment by GuenterNo** [comment]
Tested with ESP32, MCP2003 and automotive LIN devices: ok.
